### ISSUE TITLE
Support callback parameters

### ISSUE THREAD

**Issue by jcoffland** [yyx990803/vue#722]
I understand that it's possible to communicate between parent and child components via events but it would be very convenient if vue.js supported what I'm calling *callback attributes*.  This would allow you to write HTML something like this:

```
<parent-component>
  <child-component on-callback="doSomething">
  </child-component>
</parent-component>
```

With Javascript code like this:

```
var parent = {
  methods: {
    doSomething: function (args) {
      // Do something
    }
  }
}

var child = {
  cbAttributes: ['on-callback'],

  ready: function () {
    this.onCallback(/* Args */);
  }
}

$(function () {
  new Vue({
    el: 'body',

    components: {
      'parent-component': parent,
      'child-component': child,
    }
  }
})
```

Currently, I can fake this using ```paramAttributes``` by passing the function name as a string and then calling the function from the child like this:

```
this.$parent[this.onCallback](/* args */);
```

but it would be much nicer if this was explicitly supported.

I've tried passing callbacks as ```paramAttributes``` like this:

```
<parent-component>
  <child-component on-callback="{{doSomething}}">
  </child-component>
</parent-component>
```

but it does not seem to work.

Also, I want to point out that this does not couple the parent and child.

I searched for similar issues but did not find one.  I apologize in advance if this is a duplicate.

**Comment by yyx990803** [comment]
It looks like you are looking for `v-events`: http://vuejs.org/api/directives.html#v-events

**Comment by jcoffland** [comment]
@yyx990803, you are right this is pretty much what I'm after.  However, it's interesting to note that ```attrParameters``` are compiled down to ```v-with``` directives.  It would be cool if there were a way to do the same thing where something like ```attrEvents``` were compiled down to ```v-events``` and you could use cleaner syntax like:

```
<child-component on-callback="doSomething"/>
```

instead:

```
<child-component v-events="on-callback:doSomething"/>
```

BTW, I really love this framework.  You've managed to create an elegant, well documented and easily comprehensible software with an economy of features.  I previously used Angular and finally realized that despite being supported by Google and widely recommend it's an inelegant, overcomplicated, inefficient mess.  I was also interested in Mithril but ultimately was turned off by the idea of being forced to template HTML in Javascript.  I use Jade and this works well with vue.js.  

My frontend software stack currently consists of Vue.js, JQuery, Jade, Stylus, Autoprefixer, Browserify and GNU Make.  This setup is working really well.  Moving to vue.js has been a breath of fresh air.

**Comment by jcoffland** [comment]
I just noticed that there is one significant difference between ```v-events``` and the feature I originally proposed.  ```$emit``` does not allow the caller to get a return value.  Since the usual case is that there is only one receiver, this can be a significant disadvantage.

For example, say I've got an ```on-save``` callback and the child needs to either confirm or reject changes based on the success of the callback which may require contacting the server and/or user interaction.  This can be easily handled by the parent returning a promise when the ```on-save``` callback is called.  However with ```v-events``` this is not possible.

Granted this could be solved by the parent responding with a broadcast event but then you need more event handlers, a context and possibly a way to differentiate children of the same type.

**Comment by yyx990803** [comment]
It actually does: http://vuejs.org/api/instance-methods.html#Events
Additional arguments provided to `$emit` will be passed on to the callback.

**Comment by jcoffland** [comment]
I'm talking about return values.

**Comment by yyx990803** [comment]
Oh I see, I misread that. The case for Promise is valid but I'm not sure if it's worth adding a specific options/syntax for. On the other hand it's possible to use simple callbacks with `$emit`:

``` js
// parent
methods: {
  doSomething: function (cb) {
    // do something...
    cb(result)
  }
}
// child
this.$emit('event', function (result) {
  // parent done
})
```

**Comment by jcoffland** [comment]
Ok, callbacks are not a bad option.  I still like the idea of a ```cbAttributes``` option.  It could really simplify parent/child interaction with out coupling them.

**Comment by yyx990803** [comment]
I think this could easily be implemented as a mixin - just that including it in core would feel redundant with `v-events`.

**Comment by jcoffland** [comment]
I understand your reluctance to add features but it does parallel the way ```v-with``` and ```paramAttributes``` work together.   Ignoring the ability to return data, ```cbAttributes``` would be just like ```paramAttributes``` but for ```v-events```.  Just a thought.

**Comment by calebboyd** [comment]
I agree with the user-land plugin suggestion. If anything more of core should be plugins :)

**Comment by jcoffland** [comment]
I agree with keeping vue.js simple but plugins require extra boilerplate code and increase page startup time due to loading of extra .js files.  They also don't follow the same release schedule and so create an added maintenance headache.  Then there's the issue of keeping plugins up to date which has become a problem in every project I've ever used which has a significant number of plugins.

**Comment by yyx990803** [comment]
@jcoffland I've been thinking about making the template syntax cleaner, and after taking another look at the proposal, I now think this makes sense. I start to feel that `v-on` and `v-events` do not actually fall in the same category with other directives such as `v-attr`, `v-style` and `v-class`, and they deserve better , more semantic syntax.

I want to support both DOM events and Vue component events, so it gets a bit tricky when it comes to naming - I think `on-click="handler"` is very clean and well suited for DOM events, but that means we need to use a different syntax for Vue event handlers. Currently I'm thinking about `on-event-*="method"`, so it would look like this:

``` html
<!-- normal DOM events -->
<button on-click="toggle">toggle</button>

<!-- Vue events (only available on components) -->
<my-component on-event-callback="doSomething"></my-component>
```

**Comment by fullfs** [comment]
@yyx990803 
The proposed way looks good, but it would impose some restrictions to event naming. Right now I can use complex event names like "namespace.eventName" or "action:submit" etc. With ```on-event-notify="doSomething"``` those are not possible I guess. Though it may be a good thing.
P.S. I agree with @jcoffland, having something like ```cbAttributes``` would be nice.

**Comment by azamat-sharapov** [comment]
I agree that it's cleaner than current directives: `v-on="click: toggle"` vs `on-click="toggle"`. One disadvantages I see, is conflict with `props` - you can't name prop like `on-click` (onClick) for example. I have never named props like that, but some people may.. Highlighting this caveat in guide would be helpful though.

**Comment by dmarko484** [comment]
I like the 'v-' prefixes as it simply says to reader that its Vue attribute/syntax here ... and makes a some kind of Vue namespace here

**Comment by mark-hahn** [comment]
> I like the 'v-' prefixes as it simply says to reader that its Vue attribute/syntax here ... and makes a some kind of Vue namespace here

+1

**Comment by yyx990803** [comment]
@azamat-sharapov you can only pass in data with props, so a prop name like `on-click` doesn't make much sense. Internally we can throw a warning when people actually name their props with `on-`.

**Comment by azamat-sharapov** [comment]
Yeah, I know, but not everyone is english speaker around the globe :) Warning would be good, yes.

**Comment by uwe** [comment]
I agree with @dmarko484 - the 'v-' prefix is good.

**Comment by OEvgeny** [comment]
I think Vue events are different from DOM events. Now we have cleaner separation here. And that's good for me. If Vue will have similar to DOM event system, I would prefer another way. But I like how events looks now.
New event attributes looks good, but not so usable for me.

**Comment by steffans** [comment]
I prefer the 'v-' prefix for all Vue related attributes/properties.

**Comment by kazupon** [comment]
I prefer the `v-` prefix.

**Comment by azamat-sharapov** [comment]
Prefix is useful. When working in team, I tell designer colleagues not to mess with anything `v-` prefixed :) So, what about `v-on-click` and `v-event-notify` then? too long? 

Also, since everybody prefers prefix, how about changing everything vue related in HTML to have prefix? for example `options` directive doesn't have prefix, or `keep-alive`, `wait-for`, `transition-mode`, `inline-template`...

**Comment by OEvgeny** [comment]
@azamat-sharapov Depending to the docs: ``keep-alive``, ``wait-for``... are directive params.

**Comment by OEvgeny** [comment]
Since ``v-with`` was deprecated we have only one component related directive and it is ``v-events``.

**Comment by azamat-sharapov** [comment]
@OEvgeny thanks for reminding, but `wait-for` is not "directive param", because it takes argument ;) Anyway, I'm saying:

> about changing *everything vue related in HTML* to have prefix

If you ask me, I'm ok to have them without prefix anyway. Some of them sound weird with prefix.

**Comment by OEvgeny** [comment]
@azamat-sharapov you also said:
> ``options`` directive doesn't have prefix, or ``keep-alive``, ``wait-for``

Only ``v-events`` sounds weird for me. I like ``v-prefix``.

**Comment by azamat-sharapov** [comment]
@OEvgeny I only meant `options` directive and other items to be "things", as I earlier said "everything vue related". **But**, let's not argue here both being non-native english speakers ;) You also said:

> Depending to the docs 

and probably meant "According to docs". Anything related to our language/grammar or terminology mistakes should not be discussed here.

**Comment by OEvgeny** [comment]
@azamat-sharapov 
I just want to say that ``options`` and others from your list are directive params (ok according to docs). It is the reason why they don't have prefixes and I hope will not :)
My English is bad, I know. And I agree about mistakes. Sorry.

**Comment by yyx990803** [comment]
Looks like the community prefers to stick with current syntax. I think it's worth giving `v-events` a better, clearer name (changed to `v-callbacks`), but we are not going to move forward with the `on-` prefix.

**Comment by jcoffland** [comment]
I agree with sticking with the ```v-``` prefix for vue.js directives but what about the original feature request?  The user can already create their own parameters, not in the ```v-``` namespace, via ```paramAttributes```.  This issue was asking for the ability to create user defined callbacks in a similar manner, perhaps using a component option named ```cbAttributes```.

**Comment by young-steveo** [comment]
I'm not a big fan of `cbAttributes`.

* The functionality can be pretty much achieved using `v-events`; v0.12 has already come a long way in reducing the api by removing multiple ways of doing the same thing.
*  The `cb` abbreviation is not entirely clear unless you already know for what `cbAttributes` is used.

The `cbAttributes` functionality would be a good candidate for a mixin if it was really desired.

**Comment by yyx990803** [comment]
@jcoffland as you mentioned in your original proposal, the usage can already be simulated by directly calling it on the $parent, and that should be easy to abstract as a mixin. Although I like the idea as well, this is mostly a style preference, and it seems most others prefer the directive style. Also, as @young-steveo mentioned, I'd like to avoid Vue's official API having multiple ways of doing the same thing, so it's best left in userland for those who strongly prefer this style.

**Comment by jcoffland** [comment]
I agree with keeping the API simple, this is where angular went wrong.  Still I'm bothered by the squirrelly nature of the event system vs. direct callbacks.  As I mentioned above return values are not supported.   The other thing I don't like is that events run up and down the tree if they are not caught and explicitly stopped.  If you have a component which emits an event which you don't use, this event runs willy nilly around the component tree.  With direct callbacks this does not happen.  In most cases you only have one receiver, this should be the easy (default) case.  With events, multiple receivers is the default.  This is also why we need three different functions, ```$broadcast()```, ```$dispatch()``` & ```$emit()```, to emit events in the first place.  If you could wire components together explicitly with method callbacks the code would be more readable and simpler, IMHO.

Note, that my work around where you call the parent's method works if you want to map the callback to the parent but it would also be nice to be able to map callbacks to siblings using their ref ID.  For example:

```
<parent-component>
  <fancy-button v-ref="child1" on-trigger="child2.open"></fancy-button>
  <fancy-modal v-ref="child2" on-response="modalResponse"></fancy-modal>
</parent-component>
```
In the above example, ```fancy-button``` defines the callback ```on-trigger``` which the user maps to ```fancy-modal```.  ```fancy-modal``` defines the callback ```on-response``` which is mapped to ```parent-component```'s ```modalResponse``` method.  I would also like to be able to put expressions in callbacks.

**Comment by yyx990803** [comment]
Aha, I just realized what you wanted to do already works in 0.12 due to the internal compilation improvements: http://jsfiddle.net/7m3rc5L8/

**Comment by yyx990803** [comment]
It even works with your sibling calling idea: http://jsfiddle.net/7m3rc5L8/1/

**Comment by jcoffland** [comment]
That's awesome.  That looks like pretty much exactly what I'm looking for.  Is there any documentation on this syntax?

**Comment by yyx990803** [comment]
It's just the same as normal props, except now you can pass down methods too. (And methods are auto-bound to the parent)

**Comment by jcoffland** [comment]
Got it, thanks!  I tried passing down methods with ```paramAttributes``` in the very beginning.  This is great.  It allows you to do what I was asking for with ```cbAttributes``` with out adding an extra option.  I never really liked ```paramAttributes``` as a name anyway.  ```cbAttributes``` was just an attempt to conform to the existing scheme.  I like ```props``` better.

I tried to run your fiddles but they don't work because I cannot load 0.12.  Although it appears to run, in the browser console I get ```TypeError: this.onLoad is not a function```.  The expression in ```on-load``` is run because the expression is evaluated by vue.js at load time not because of the function call.

Does this usage work with return values?  E.g. like this: http://jsfiddle.net/sr7n8jry/

**Comment by yyx990803** [comment]
The call to `sibling.doSomething` had braces so it was treated as a statement with no return value. If you remove the braces it will work: http://jsfiddle.net/sr7n8jry/1/

**Comment by jcoffland** [comment]
Oh, I see.  You mean parenthesis not braces though.

**Comment by yyx990803** [comment]
oops, yes :)

**Comment by ErikWitkowski** [comment]
guys how we do this today with Vue v2?
